// src/components/ToggleThemeButton.tsx
import React from "react";
import { FaMoon } from "react-icons/fa";
import halfmoon from "halfmoon";

export const ToggleThemeButton = () => (
  <div
    className="btn btn-action mr-5"
    onClick={() => halfmoon.toggleDarkMode()}
    data-test-id="toggle-theme-button"
    data-toggle="tooltip"
    data-placement="left"
    data-title="Toggle Dark Mode"
  >
    <FaMoon />
  </div>
);

// src/components/ToggleThemeButton.svelte
<script>
  import halfmoon from "halfmoon";
  import Fa from "svelte-fa";
  import { faMoon } from "@fortawesome/free-solid-svg-icons";
</script>

<div
  class="btn btn-action mr-5"
  on:click={() => halfmoon.toggleDarkMode()}
  data-test-id="toggle-theme-button"
  data-toggle="tooltip"
  data-placement="left"
  data-title="Toggle Dark Mode"
>
  <Fa icon={faMoon} />
</div>
